name: Test

on:
    push:
        branches: [master, next]
    pull_request:
        branches: ["master", "next"]

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                experimental: [false] # Shadow CI Jobs
                node: ["18", "20"] # Refer to https://nodejs.org/en/about/releases/ for supported versions

        name: Test on Node v${{ matrix.node }}
        continue-on-error: ${{ matrix.experimental }}
        steps:
            - uses: szenius/set-timezone@v1.2
              with:
                  timezoneLinux: "Etc/GMT-2"

            - uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
                  cache: "yarn"

            - name: Setup ignore engines flag for yarn
              run: yarn config set ignore-engines true

            - name: Cache node modules
              uses: actions/cache@v3
              id: cache-modules
              env:
                  cache-name: cache-node-${{ matrix.node }}-modules
              with:
                  path: ./node_modules
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-

            - name: Install dependencies
              if: steps.cache-modules.outputs.cache-hit != 'true'
              run: yarn install --prefer-offline --frozen-lockfile

            - name: Run tests
              run: yarn test:ci

            - name: Collect coverage
              uses: codecov/codecov-action@v3
              with:
                  fail_ci_if_error: true
                  flags: Node-v${{ matrix.node }}
